@ASPNETCoreWebApiNativeAOTWithoutTopLevelStatements_HostAddress = http://localhost:5197

GET {{ASPNETCoreWebApiNativeAOTWithoutTopLevelStatements_HostAddress}}/todos/
Accept: application/json

###

GET {{ASPNETCoreWebApiNativeAOTWithoutTopLevelStatements_HostAddress}}/todos/1
Accept: application/json

###
